version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: "influxdb"
    ports:
      - '8086:8086'
    volumes:
      - /data:/var/lib/influxdb2
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=skanestas
      - DOCKER_INFLUXDB_INIT_BUCKET=tickers
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token-test

    networks:
      - my-network

  backend:
    build: ./tickers
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - influxdb
    networks:
      - my-network

  frontend:
    build: ./visualisation
    container_name: frontend
    ports:
      - "8050:8050"
    restart: always
    depends_on:
      - influxdb
      - backend
    networks:
      - my-network

volumes:
  influxdb-storage:
    external: true
  data:

networks:
  my-network:
    driver: bridge
